const router=require('express').Router();const prisma=require('../config/database');const {auth,requireRole}=require('../middleware/auth');
router.get('/',auth,async(req,res,next)=>{try{const [badges,classement]=await Promise.all([
  prisma.badge.findMany({orderBy:{seuilEcoPoints:'asc'}}),
  prisma.citoyen.findMany({include:{utilisateur:{select:{id:true,nom:true,email:true}}},orderBy:{ecoPoints:'desc'},take:10})
]);res.json({badges,classement:classement.map((c,i)=>({rang:i+1,id:c.id,ecoPoints:c.ecoPoints,niveau:c.niveau,utilisateur:c.utilisateur}))});}catch(e){next(e)}});
router.get('/badges',auth,async(req,res,next)=>{try{res.json(await prisma.badge.findMany({orderBy:{seuilEcoPoints:'asc'}}));}catch(e){next(e)}});
router.post('/badges',auth,requireRole('admin','agent'),async(req,res,next)=>{try{const {nom,description,iconeUrl,seuilEcoPoints=100}=req.body;if(!nom)return res.status(422).json({detail:'nom est requis.'});const b=await prisma.badge.create({data:{nom,description:description||null,iconeUrl:iconeUrl||null,seuilEcoPoints:Number(seuilEcoPoints)}});res.status(201).json(b);}catch(e){next(e)}});
router.get('/classement',auth,async(req,res,next)=>{try{const rows=await prisma.citoyen.findMany({include:{utilisateur:{select:{id:true,nom:true,email:true}}},orderBy:{ecoPoints:'desc'}});res.json(rows.map((c,i)=>({rang:i+1,id:c.id,ecoPoints:c.ecoPoints,niveau:c.niveau,utilisateur:c.utilisateur})));}catch(e){next(e)}});
router.get('/mes-badges',auth,async(req,res,next)=>{try{const c=await prisma.citoyen.findUnique({where:{utilisateurId:req.user.id},include:{badgesAcquis:{include:{badge:true}}}});if(!c)return res.status(404).json({detail:'Profil citoyen introuvable.'});res.json(c.badgesAcquis.map(b=>b.badge));}catch(e){next(e)}});
router.post('/badges/:badgeId/attribuer',auth,requireRole('admin','agent'),async(req,res,next)=>{try{const {citoyenId}=req.body;if(!citoyenId)return res.status(422).json({detail:'citoyenId est requis.'});const {badgeId}=req.params;const exist=await prisma.badgeAcquis.findUnique({where:{badgeId_citoyenId:{badgeId:Number(badgeId),citoyenId:Number(citoyenId)}}});if(exist)return res.status(409).json({detail:'Badge déjà acquis par ce citoyen.'});const ba=await prisma.badgeAcquis.create({data:{badgeId:Number(badgeId),citoyenId:Number(citoyenId)}});res.status(201).json(ba);}catch(e){next(e)}});
module.exports=router;
